apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp
  labels:
    app: orderapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapp
  template:
    metadata:
      labels:
        app: orderapp
    spec:
      containers:
        - name: orderapp
          image: thaboatdev/user-info-service:latest
          imagePullPolicy: Always
          ports:
           - containerPort: 9094
          env:
           - name: JAVA_TOOL_OPTIONS
             value: "-Djkd.tls.client.protocols=TLSv1.2"
           - name: SPRING_DATA_MONGODB_URI
             valueFrom:
                configMapKeyRef:
                  name: configmap
                  key: orderdb_url
           - name: SPRING_DATA_MONGODB_DATABASE
             value: "orderdb"

---
apiVersion: v1 
kind: Service 
metadata:
  name: foodcatalogue-service 
spec:
  ports:
    - protocol: TCP
      port: 9094
      targetPort: 9094
  selector:
    app: orderapp


